# Terraform/development/kubernetes/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world-app
        # This image name is a placeholder that Jenkins will replace
        image: your-registry/hello-world-app:latest
        ports:
        - containerPort: 8080
