apiVersion: v1
kind: Service
metadata:
  # The name of the service
  name: hello-world-service
  # The namespace where the service will be created, should match the deployment
  namespace: development
spec:
  # This type creates an external cloud load balancer to expose the service.
  # This directly fulfills the "Load Balancer" requirement.
  type: LoadBalancer

  selector:
    # This selector must match the labels of the pods created by the deployment.yaml.
    # It tells the service which pods to send traffic to.
    app: hello-world

  ports:
    - protocol: TCP
      # The port that the load balancer will listen on. Port 80 is standard for HTTP.
      port: 80
      # The port on the pods that traffic will be forwarded to.
      # This must match the containerPort in your deployment.yaml.
      targetPort: 8080
